# ArgoCD Application to manage ingress-nginx
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: europe-west4-docker.pkg.dev/sandbox-9456/helm
      chart: ingress-nginx
      targetRevision: 4.12.2
      helm:
        valueFiles:
          - $values/values.yaml
    - repoURL: https://github.com/JulianDerksOrg/xebia-demo-ingress-nginx-kube-live.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
